services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.2"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: gem_cache
        target: /usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/app/.bundle
    command: rake build

  test-install:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RUBY_VERSION: "3.2"

volumes:
  gem_cache:
    name: go_snowflake_ruby_gem_cache
  test_gem_cache:
    name: go_snowflake_ruby_test_cache
